# frozen_string_literal: true

Dir[File.join(Rails.root, 'db', 'seeds', '*.rb')].each { |seed| load seed }

RelationType.create(code: 'married',   name: 'брак')
RelationType.create(code: 'divorced',  name: 'развод')

Role.create(code: 'owner',   name: 'Владелец')
Role.create(code: 'editor',  name: 'Редактор')
Role.create(code: 'guest',   name: 'Гость')

Sex.create(code: 'male',     name: 'муж.')
Sex.create(code: 'female',   name: 'жен.')

InfoType.create(code: 'disease',           name: 'болезнь')
InfoType.create(code: 'idols',             name: 'кумиры')
InfoType.create(code: 'interests',         name: 'личность и интересы')
InfoType.create(code: 'food',              name: 'любимая еда')
InfoType.create(code: 'music_books',       name: 'музыка, книги')
InfoType.create(code: 'films',             name: 'фильмы')
InfoType.create(code: 'quotes',            name: 'цитаты')
InfoType.create(code: 'politics',          name: 'политика')
InfoType.create(code: 'employer',          name: 'работодатель')
InfoType.create(code: 'religion',          name: 'религия')
InfoType.create(code: 'occupation',        name: 'род занятий')
InfoType.create(code: 'sport',             name: 'спорт')
InfoType.create(code: 'hobbies',           name: 'увлечения')
InfoType.create(code: 'academic_degree',   name: 'ученая степень')
InfoType.create(code: 'hobby',             name: 'хобби')
InfoType.create(code: 'language',          name: 'язык общения')

RelationshipType.create(code: 'husband',   name: 'муж')
RelationshipType.create(code: 'wife',      name: 'жена')
RelationshipType.create(code: 'son',       name: 'сын')
RelationshipType.create(code: 'daughter',  name: 'дочь')
RelationshipType.create(code: 'brother',   name: 'брат')
RelationshipType.create(code: 'sister',    name: 'сестра')
RelationshipType.create(code: 'father',    name: 'отец')
RelationshipType.create(code: 'mother',    name: 'мать')

FactType.create(code: 'birth',          name: 'Рождение',                     for_man: 'Родился',            for_woman: 'Родилась')
FactType.create(code: 'christening',    name: 'Крещение',                     for_man: 'Крещен',             for_woman: 'Крещена')
FactType.create(code: 'marriage',       name: 'Брак',                         for_man: 'Женился',            for_woman: 'Вышла замуж')
FactType.create(code: 'death',          name: 'Смерть',                       for_man: 'Умер',               for_woman: 'Умерла')
FactType.create(code: 'burial',         name: 'Захоронение',                  for_man: 'Похоронен',          for_woman: 'Похоронена')
FactType.create(code: 'military',       name: 'Военная служба',               for_man: 'Служил',             for_woman: 'Служила')
FactType.create(code: 'demobilization', name: 'Демобилизация',                for_man: 'Демобилизован',      for_woman: 'Демобилизована')
FactType.create(code: 'reward',         name: 'Награда',                      for_man: 'Награжден',          for_woman: 'Награждена')
FactType.create(code: 'citizenship',    name: 'Принятие гражданства',         for_man: 'Принял гражданство', for_woman: 'Приняла гражданство')
FactType.create(code: 'moving',         name: 'Переезд',                      for_man: 'Переехал',           for_woman: 'Переехала')
FactType.create(code: 'education',      name: 'Образование',                  for_man: 'Учился',             for_woman: 'Училась')
FactType.create(code: 'graduation',     name: 'Окончание учебного заведения', for_man: 'Окончил',            for_woman: 'Окончила')
FactType.create(code: 'work',           name: 'Работа',                       for_man: 'Работал',            for_woman: 'Работала')
FactType.create(code: 'divorce',        name: 'Развод',                       for_man: 'Развелся',           for_woman: 'Развелась')
FactType.create(code: 'retirement',     name: 'Уход на пенсию',               for_man: 'Ушел на пенсию',     for_woman: 'Ушла на пенсию')
FactType.create(code: 'academic',       name: 'Ученая степень',               for_man: 'Получил степень',    for_woman: 'Получила степень')
FactType.create(code: 'other',          name: 'Другое',                       for_man: 'Другое',             for_woman: 'Другое')
